package com;
import com.example.model.Customer;
import com.example.model.Deal;

global com.example.model.PrefSetting prefSetting;
global com.example.model.FilterResultSet filterResultSet;

// dialect "mvel"


rule 'industry'
    // salience 1
    when
        $customer: Customer()
        if ( industry == prefSetting.getIndustry()) break[success]
    then
        System.out.println("Printing customers that has failed the industry filter" + $customer.getId());
        then[success]
            System.out.println("Printing customers that has passed the industry filter" + $customer.getId());
            filterResultSet.setVariable($customer.getId());
            // System.out.println("Printing filterResultSet" + filterResultSet.getPassSet());
end
        


rule 'sub industry'
    // salience 1
    when
        $customer: Customer()
        // if (prefSetting.getSubIndustry().contains(subIndustry) ) break[success]
        if (filterResultSet.getPassSet().contains(id) && 
            prefSetting.getSubIndustry().contains(subIndustry) ) break[success]
    then
        System.out.println("Printing customers that has failed the sub_industry filter" + $customer.getId());
        then[success]
            System.out.println("Printing customers that has passed the sub_industry filter" + $customer.getId());
end


rule 'amount'
    when
        $amount: Deal()
        if ( amount >= prefSetting.getMinAmount() && amount <= prefSetting.getMaxAmount())  break[success]
    then
        System.out.println("Amount not Matched successfully"+ $amount.getId());
        then[success]
            System.out.println("amount Matched successfully"+ $amount.getId());
end


rule 'roi'
    when
        $roi: Deal()
        if ( roi >= prefSetting.getMinAmount() && roi <= prefSetting.getMaxAmount())  break[success]
    then
        System.out.println("Roi not Matched successfully"+ $roi.getId());
        then[success]
            System.out.println("Roi Matched successfully"+ $roi.getId());
end



rule 'tenor'
    when
        $tenor: Deal()
        if ( tenor >= prefSetting.getMinAmount() && tenor <= prefSetting.getMaxAmount())  break[success]
    then
        System.out.println("Roi not Matched successfully"+ $tenor.getId());
        then[success]
            System.out.println("Roi Matched successfully"+ $tenor.getId());
end